# Site settings
title: Joby Joseph
tag_text: 404
description: This is supposed to be a personal website but i am too lazy to actually build a proper one. 

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
